### ISSUE TITLE
Only build library part

### ISSUE THREAD

**Issue by jbieler** [praetoriandroid/sony-camera-remote-java#1]
Hello,

is it possible to build just the library without any android dependencies?

**Comment by praetoriandroid** [comment]
Hello,

Sure, just run `./gradlew :sony-camera-remote-lib:build` and you'll get the `sony-camera-remote-lib/build/libs/sony-camera-remote-lib-0.1.0.jar library`.

**Comment by praetoriandroid** [comment]
Oh, to build the command-line tool run `./gradlew :command-line-tool:build`. To run the command-line tool do `java -jar command-line-tool/build/libs/cameraremote-tool-0.1.0.jar `.
